const KEY = 'snowVanillaDataV1';
const uid = () => `${Date.now().toString(36)}${Math.random().toString(36).slice(2,7)}`;
const now = () => new Date().toISOString();
const defaults = () => ({
  version: 1,
  ui: { fontSize: 15, active: 'chat', activeRole: 'role-1' },
  roles: [{ id:'role-1', name:'角色', avatar:'', status:'在这里，等你说话', permissions:{ text:['温柔日常'], sticker:true, emoji:true, kaomoji:true, poke:true, status:true }, settings:{ proactiveSeconds:0, replySpeed:2, momentMin:0, momentMax:0, voiceChance:0, videoChance:0, pokeChance:10, favoriteChance:15, giftChance:0, read:true, noReply:false, combine:false, combineMin:2, combineMax:3, fontSize:15, userCss:'', roleCss:'' } }],
  cards: { textGroups:[{id:'g1',name:'温柔日常',items:['今天也有好好想你。','慢慢来，我一直在。','想听你多说一点。'],roles:['role-1']}], sticker:[], emoji:[{id:uid(),text:'♡',roles:['role-1']}], kaomoji:[{id:uid(),text:'(｡•ᴗ•｡)',roles:['role-1']}], poke:[{id:uid(),text:'轻轻碰了碰你',roles:['role-1']}], status:[{id:uid(),text:'在这里，等你说话',roles:['role-1']}] },
  chats:{'role-1':[{id:uid(),from:'role',type:'text',content:'今天也有好好想你。',time:now()}]},
  moments:[], favorites:{role:[],mine:[]}, gifts:[], dreams:[], schedule:[], anniversaries:[], notes:[],
  global:{readStyle:'text'}
});
let db = load(), modal = null, cardTab = 'text', timer = null, callState = null;
function load(){ try { const saved=JSON.parse(localStorage.getItem(KEY)); return saved?.version ? saved : defaults(); } catch { return defaults(); } }
function save(){ localStorage.setItem(KEY,JSON.stringify(db)); document.documentElement.style.setProperty('--font',`${db.ui.fontSize}px`); }
function icon(name){ return `<svg class="icon" aria-hidden="true"><use href="#i-${name}"></use></svg>`; }
function role(){ return db.roles.find(r=>r.id===db.ui.activeRole)||db.roles[0]; }
function avatar(r=role()){ return `<div class="avatar" data-poke="${r.id}">${r.avatar?`<img src="${r.avatar}" alt="${esc(r.name)}">`:esc(r.name)}</div>`; }
function esc(v=''){ const d=document.createElement('div');d.textContent=String(v);return d.innerHTML; }
function time(v){ return new Date(v).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}); }
function pick(a){ return a?.length?a[Math.floor(Math.random()*a.length)]:null; }
function chance(n){ return Math.random()*100<n; }
function toast(s){ const e=document.createElement('div');e.className='toast';e.textContent=s;document.querySelector('.app').append(e);setTimeout(()=>e.remove(),1800); }
function header(title,left='',right=''){ return `<header class="topbar"><div class="side">${left}</div><h1>${esc(title)}</h1><div class="side">${right}</div></header>`; }
function bnav(){ return `<nav class="bottom">${[['chat','chat'],['cards','cards'],['moments','spark'],['dreams','heart'],['me','user']].map(([id,ic])=>`<button class="nav-btn ${db.ui.active===id?'active':''}" data-nav="${id}" aria-label="${id}">${icon(ic)}</button>`).join('')}</nav>`; }
function render(){ save(); const views={chat:chatView,cards:cardsView,moments:momentsView,dreams:dreamsView,me:meView}; document.getElementById('app').innerHTML=`<div class="app">${views[db.ui.active]()}${bnav()}${modal?modalView():''}${callState?callView():''}</div>`; bind(); }
function chatView(){ const r=role(),msgs=db.chats[r.id]||[]; return `${header(r.name,`<button class="icon-btn" data-open="roles">${avatar(r)}</button>`,`<button class="icon-btn" data-action="search">${icon('search')}</button><button class="icon-btn" data-open="settings">${icon('settings')}</button>`)}<main class="main chat-main"><div class="chat-scroll" id="chatScroll">${msgs.length?msgs.map((m,i)=>message(m,i)).join(''):'<div class="empty">从一句问候开始吧</div>'}</div><form class="composer" id="composer"><button type="button" class="icon-btn" data-open="tools">${icon('plus')}</button><input name="message" autocomplete="off" placeholder="写下想说的话…"><button class="icon-btn send">${icon('send')}</button></form></main>`; }
function message(m,i){ if(m.type==='notice')return `<div class="notice" id="msg-${m.id}">${esc(m.content)}</div>`; const r=role(), style=m.from==='me'?r.settings.userCss:r.settings.roleCss; return `${i===0||new Date(m.time)-new Date((db.chats[r.id][i-1]||{}).time)>300000?`<div class="message-time">${time(m.time)}</div>`:''}<div class="msg ${m.from==='me'?'me':''}" id="msg-${m.id}" data-message="${m.id}">${avatar(m.from==='me'?{id:'me',name:'我',avatar:''}:r)}<div><div class="bubble" style="${esc(style)}">${m.type==='image'?`<img class="moment-img" src="${m.content}" alt="图片">`:esc(m.content)}</div>${m.from==='me'&&m.read?`<div class="receipt">${receipt()}</div>`:''}</div></div>`; }
function receipt(){ return db.global.readStyle==='checks'?'✓✓':db.global.readStyle==='heart'?'♥':'已读'; }
function rolesView(){ return `<div class="section-title"><h2>我的角色</h2><button class="icon-btn" data-action="add-role">${icon('plus')}</button></div><div class="role-list">${db.roles.map(r=>`<button class="card role-row" data-role="${r.id}">${avatar(r)}<div class="grow" style="text-align:left"><div class="name">${esc(r.name)}</div><div class="status">${esc(r.status)}</div></div>${icon('chevron')}</button>`).join('')}</div>`; }
function cardsView(){ const tabs=[['text','文字'],['sticker','表情包'],['emoji','emoji'],['kaomoji','颜文字'],['poke','拍一拍'],['status','状态']]; return `${header('字卡库','',`<button class="icon-btn" data-action="card-add">${icon('plus')}</button>`)}<main class="main"><div class="hero card"><span class="eyebrow">Memory library</span><h2>只说你写过的话</h2><p>所有回应均从允许的字卡中随机抽取，不连接任何 AI。</p></div><div class="tabs">${tabs.map(t=>`<button class="tab ${cardTab===t[0]?'active':''}" data-cardtab="${t[0]}">${t[1]}</button>`).join('')}</div>${cardList()}</main>`; }
function cardList(){ if(cardTab==='text') return db.cards.textGroups.map(g=>`<section class="card"><div class="section-title" style="margin:0 0 8px"><h2>${esc(g.name)}</h2><div><button class="tiny-btn" data-editgroup="${g.id}">${icon('edit')}</button><button class="tiny-btn" data-delgroup="${g.id}">${icon('trash')}</button></div></div><div class="muted" style="font-size:12px">${g.roles.map(id=>db.roles.find(r=>r.id===id)?.name).filter(Boolean).join('、')||'未授权角色'}</div>${g.items.map((x,i)=>`<div class="list-item"><div class="text">${esc(x)}</div><button class="tiny-btn" data-editcard="${g.id}:${i}">${icon('edit')}</button><button class="tiny-btn" data-delcard="${g.id}:${i}">${icon('trash')}</button></div>`).join('')}</section>`).join('')||'<div class="empty">还没有文字分组</div>'; const arr=db.cards[cardTab]; return `<section class="card">${arr.map((x,i)=>`<div class="list-item">${cardTab==='sticker'?`<img src="${x.text}" class="avatar" alt="表情包">`:`<div class="text">${esc(x.text)}</div>`}<span class="muted" style="font-size:11px">${x.roles.length} 个角色</span><button class="tiny-btn" data-edititem="${i}">${icon('edit')}</button><button class="tiny-btn" data-delitem="${i}">${icon('trash')}</button></div>`).join('')||'<div class="empty">点击右上角添加</div>'}</section>`; }
function momentsView(){ return `${header('朋友圈','',`<button class="icon-btn" data-open="moment-add">${icon('plus')}</button>`)}<main class="main"><div class="hero card"><span class="eyebrow">Our little world</span><h2>落雪般的日常</h2><p>你和角色都可以在这里留下生活片段。</p></div>${db.moments.map(m=>`<article class="card moment"><div class="moment-head">${avatar(m.author==='me'?{id:'me',name:'我'}:db.roles.find(r=>r.id===m.author))}<div class="grow"><b>${m.author==='me'?'我':esc(db.roles.find(r=>r.id===m.author)?.name||'角色')}</b><div class="status">${new Date(m.time).toLocaleString()}</div></div><button data-delmoment="${m.id}" class="tiny-btn">${icon('trash')}</button></div><p>${esc(m.text)}</p>${m.image?`<img class="moment-img" src="${m.image}" alt="动态图片">`:''}<div class="moment-foot"><button data-like="${m.id}">${icon('heart')} ${m.likes||0}</button><span>${(m.comments||[]).length} 条评论</span></div></article>`).join('')||'<div class="empty">还没有动态，记录第一个瞬间吧。</div>'}</main>`; }
function dreamsView(){ return `${header('梦境记录','',`<button class="icon-btn" data-open="dream-add">${icon('plus')}</button>`)}<main class="main"><div class="hero card"><span class="eyebrow">Dream archive</span><h2>把梦留在醒来以前</h2><p>沿着时间线，收藏只属于你们的片段。</p></div><div class="timeline">${db.dreams.map(d=>`<article class="card"><small class="muted">${esc(d.date)}</small><h3>${esc(d.title)}</h3><p>${esc(d.text)}</p><button class="tiny-btn" data-deldream="${d.id}">${icon('trash')}</button></article>`).join('')||'<div class="empty">昨夜做了什么梦？</div>'}</div></main>`; }
function meView(){ return `${header('更多空间')}<main class="main"><div class="card role-row">${avatar()}<div class="grow"><div class="name">Snow Vanilla</div><div class="status">本机保存 · 不使用 AI</div></div></div><div class="grid-tools">${[['favorites','heart','收藏'],['gifts','gift','礼物柜'],['schedule','calendar','角色日程'],['board','cards','留言板']].map(x=>`<button class="tool" data-open="${x[0]}">${icon(x[1])}${x[2]}</button>`).join('')}</div><section class="card" style="margin-top:14px"><div class="switch-row"><span>全站字体大小</span><b id="fontVal">${db.ui.fontSize}px</b></div><input class="range" data-font type="range" min="12" max="21" value="${db.ui.fontSize}"><div class="switch-row"><span>已读标识</span><select data-readstyle><option value="text">文字已读</option><option value="checks">双对勾</option><option value="heart">黑色小爱心</option></select></div><div class="actions"><button class="secondary" data-action="export">${icon('download')} 导出 JSON</button><button class="secondary" data-action="import">${icon('upload')} 导入 JSON</button></div><button class="danger" style="width:100%;margin-top:10px" data-action="clear">清空所有数据</button></section><p class="muted" style="font-size:12px;text-align:center">所有数据仅保存在当前浏览器的 localStorage 中。</p></main>`; }
function modalView(){ const body={roles:rolesView,settings:settingsForm,tools:toolsView,'moment-add':momentForm,'dream-add':dreamForm,favorites:favoritesView,gifts:giftsView,schedule:scheduleView,board:boardView,'card-add':cardForm,'role-add':roleForm}[modal]; return `<div class="overlay" data-close><section class="sheet" onclick="event.stopPropagation()"><div class="sheet-head"><h2>${modalTitle()}</h2><button class="icon-btn" data-close>${icon('x')}</button></div>${body?body():''}</section></div>`; }
function modalTitle(){ return ({roles:'切换角色',settings:'编辑角色',tools:'更多功能','moment-add':'发布动态','dream-add':'记录梦境',favorites:'收藏',gifts:'礼物展示柜',schedule:'角色日程',board:'留言板','card-add':'添加字卡','role-add':'添加角色'})[modal]||''; }
function toggle(label,key){ const s=role().settings;return `<div class="switch-row"><span>${label}</span><button class="switch ${s[key]?'on':''}" data-toggle="${key}" aria-label="${label}"></button></div>`; }
function range(label,key,min,max,unit='%'){ const v=role().settings[key]; return `<div class="field"><label><span>${label}</span><b data-value="${key}">${v}${unit}</b></label><input class="range" type="range" min="${min}" max="${max}" value="${v}" data-range="${key}" data-unit="${unit}"></div>`; }
function settingsForm(){ const r=role(),s=r.settings; return `<form id="settingsForm"><div class="card role-row">${avatar(r)}<div class="grow"><label class="eyebrow">角色昵称</label><input name="name" value="${esc(r.name)}" style="width:100%;border:0;background:transparent;font-weight:bold"></div><button type="button" class="secondary" data-action="avatar">更换头像</button></div>${range('主动消息间隔', 'proactiveSeconds',0,300,' 秒')}${range('回复速度', 'replySpeed',0,8,' 秒')}${range('朋友圈最短发布间隔','momentMin',0,3600,' 秒')}${range('朋友圈最长发布间隔','momentMax',0,7200,' 秒')}${range('主动语音通话概率','voiceChance',0,100)}${range('主动视频通话概率','videoChance',0,100)}${range('拍一拍概率','pokeChance',0,100)}${range('收藏用户消息概率','favoriteChance',0,100)}${range('主动送礼物概率','giftChance',0,100)}${toggle('显示已读','read')}${toggle('允许已读不回','noReply')}${toggle('开启拼字卡','combine')}<div class="actions"><label class="field">最少条数<input name="combineMin" type="number" min="1" value="${s.combineMin}"></label><label class="field">最多条数<input name="combineMax" type="number" min="1" value="${s.combineMax}"></label></div><div class="field"><label>角色内字体大小 <b>${s.fontSize}px</b></label><input class="range" name="fontSize" type="range" min="12" max="21" value="${s.fontSize}"></div><h3>气泡 CSS</h3><p class="muted">预览会即时变化；仅点击“保存并应用”后用于聊天。</p><div class="field"><label>我的气泡</label><textarea name="userCss" data-css="me" placeholder="例如：background:#dbe8dc;">${esc(s.userCss)}</textarea></div><div class="field"><label>角色气泡</label><textarea name="roleCss" data-css="role" placeholder="例如：border-radius:20px;">${esc(s.roleCss)}</textarea></div><div class="preview"><div class="msg role"><div class="bubble" id="rolePreview">角色的气泡预览</div></div><div class="msg me"><div class="bubble" id="mePreview">我的气泡预览</div></div></div><div class="actions"><button type="button" class="secondary" data-action="reset-settings">恢复默认</button><button class="primary">保存并应用</button></div></form>`; }
function toolsView(){ return `<div class="grid-tools">${[['image','image','图片'],['camera','video','拍照'],['sticker','cards','表情包'],['poke','user','拍一拍'],['transfer','send','转账'],['redpacket','gift','红包'],['gift-send','gift','礼物'],['share','spark','分享'],['voice','phone','语音通话'],['video','video','视频通话']].map(x=>`<button class="tool" data-tool="${x[0]}">${icon(x[1])}${x[2]}</button>`).join('')}</div><p class="muted" style="margin-top:15px">相机与视频仅在浏览器授权后启用；角色端为字卡驱动的模拟逻辑，不伪装真实远端音视频。</p>`; }
function roleChecks(selected=[]){ return db.roles.map(r=>`<label class="switch-row"><span>${esc(r.name)}</span><input type="checkbox" name="roles" value="${r.id}" ${selected.includes(r.id)?'checked':''}></label>`).join(''); }
function cardForm(){ if(cardTab==='sticker')return `<form id="stickerForm"><p>选择相册、文件或相机图片。上传后可删除；列表顺序即使用顺序。</p><input type="file" name="image" accept="image/*" capture><h3>允许使用的角色</h3>${roleChecks(db.roles.map(r=>r.id))}<button class="primary" style="width:100%;margin-top:12px">添加</button></form>`; return `<form id="cardForm">${cardTab==='text'?'<div class="field"><label>分组名称（仅手动创建）</label><input name="group" type="text" placeholder="例如：晚安"></div>':''}<div class="field"><label>批量添加，每行一条（自动去重）</label><textarea name="items" required></textarea></div><h3>允许使用的角色</h3>${roleChecks(db.roles.map(r=>r.id))}<button class="primary" style="width:100%;margin-top:12px">添加字卡</button></form>`; }
function roleForm(){ return `<form id="roleForm"><div class="field"><label>昵称</label><input name="name" value="角色" required></div><div class="field"><label>头像（可稍后在角色设置更换）</label><input name="avatar" type="file" accept="image/*" capture></div><button class="primary" style="width:100%">创建角色</button></form>`; }
function momentForm(){ return `<form id="momentForm"><div class="field"><label>文字</label><textarea name="text" placeholder="写下这一刻…"></textarea></div><div class="field"><label>本地图片 / 相机</label><input name="image" type="file" accept="image/*" capture="environment"></div><button class="primary" style="width:100%">发布</button></form>`; }
function dreamForm(){ return `<form id="dreamForm"><div class="field"><label>日期</label><input name="date" type="date" value="${now().slice(0,10)}"></div><div class="field"><label>标题</label><input name="title" required></div><div class="field"><label>梦境内容</label><textarea name="text" required></textarea></div><button class="primary" style="width:100%">保存梦境</button></form>`; }
function favoritesView(){ const all=[...db.favorites.role.map(x=>({...x,owner:'角色收藏'})),...db.favorites.mine.map(x=>({...x,owner:'我的收藏'}))];return all.map(x=>`<div class="card"><span class="eyebrow">${x.owner}</span><p>${esc(x.content)}</p></div>`).join('')||'<div class="empty">长按或右键聊天气泡即可收藏、撤回与转发。</div>'; }
function giftsView(){ return `<button class="primary" style="width:100%;margin-bottom:12px" data-action="new-gift">送一份礼物</button>${db.gifts.map(g=>`<div class="card"><span class="eyebrow">${g.from==='me'?'我送给角色':'角色送给我'}</span><h3>${esc(g.name)} · ¥${g.price}</h3><p>${esc(g.content||'')}</p><div class="actions"><button class="secondary" data-giftstatus="${g.id}:accepted">接收</button><button class="secondary" data-giftstatus="${g.id}:rejected">拒绝</button><button class="secondary" data-giftstatus="${g.id}:paid">代付</button></div><small class="muted">${g.status||'等待处理'} · 双方可在礼物下留言</small></div>`).join('')||'<div class="empty">展示柜还是空的</div>'}`; }
function scheduleView(){ const quote=pick(allowedCards('text'))||'今天，也请温柔地走向彼此。';return `<div class="hero card"><span class="eyebrow">今日寄语</span><h3>${esc(quote)}</h3></div><form id="scheduleForm"><div class="field"><label>角色每日安排 / 纪念日</label><input name="title" required placeholder="例如：第一次相遇"></div><div class="field"><input name="date" type="date" value="${now().slice(0,10)}"></div><button class="primary" style="width:100%">添加</button></form>${[...db.schedule,...db.anniversaries].map(x=>`<div class="list-item"><div class="text"><b>${esc(x.title)}</b><div class="status">${x.date}</div></div></div>`).join('')}`; }
function boardView(){ return `<div class="actions"><button class="secondary" data-action="add-note">添加小便签</button><button class="secondary" data-action="role-note">角色留言</button></div><div class="canvas" id="canvas">${db.notes.map(n=>`<div class="note ${n.from==='role'?'role':''}" data-note="${n.id}" style="left:${n.x}px;top:${n.y}px;width:${n.w||145}px;height:${n.h||100}px">${esc(n.text)}</div>`).join('')}</div><p class="muted">拖动便签更换位置，拖动右下角调整大小；位置与尺寸自动保存。</p>`; }
function bind(){
  document.querySelectorAll('[data-nav]').forEach(x=>x.onclick=()=>{db.ui.active=x.dataset.nav;modal=null;render()});
  document.querySelectorAll('[data-open]').forEach(x=>x.onclick=()=>{modal=x.dataset.open;render()});
  document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>{modal=null;render()});
  document.querySelectorAll('[data-cardtab]').forEach(x=>x.onclick=()=>{cardTab=x.dataset.cardtab;render()});
  document.querySelectorAll('[data-role]').forEach(x=>x.onclick=()=>{db.ui.activeRole=x.dataset.role;modal=null;render()});
  document.querySelectorAll('[data-action]').forEach(x=>x.onclick=e=>{e.preventDefault();action(x.dataset.action)});
  document.querySelectorAll('[data-tool]').forEach(x=>x.onclick=()=>toolAction(x.dataset.tool));
  document.querySelectorAll('[data-toggle]').forEach(x=>x.onclick=()=>{role().settings[x.dataset.toggle]=!role().settings[x.dataset.toggle];render()});
  document.querySelectorAll('[data-range]').forEach(x=>x.oninput=()=>{role().settings[x.dataset.range]=+x.value;document.querySelector(`[data-value="${x.dataset.range}"]`).textContent=x.value+x.dataset.unit;save()});
  document.querySelectorAll('[data-css]').forEach(x=>x.oninput=()=>document.getElementById(`${x.dataset.css}Preview`).style.cssText=x.value);
  const comp=document.getElementById('composer');if(comp)comp.onsubmit=sendMessage;
  const sf=document.getElementById('settingsForm');if(sf)sf.onsubmit=saveSettings;
  const cf=document.getElementById('cardForm');if(cf)cf.onsubmit=addCards;
  const st=document.getElementById('stickerForm');if(st)st.onsubmit=addSticker;
  const rf=document.getElementById('roleForm');if(rf)rf.onsubmit=addRole;
  const mf=document.getElementById('momentForm');if(mf)mf.onsubmit=addMoment;
  const df=document.getElementById('dreamForm');if(df)df.onsubmit=addDream;
  const sc=document.getElementById('scheduleForm');if(sc)sc.onsubmit=addSchedule;
  document.querySelectorAll('[data-deldream]').forEach(x=>x.onclick=()=>{db.dreams=db.dreams.filter(d=>d.id!==x.dataset.deldream);render()});
  document.querySelectorAll('[data-delmoment]').forEach(x=>x.onclick=()=>{db.moments=db.moments.filter(d=>d.id!==x.dataset.delmoment);render()});
  document.querySelectorAll('[data-like]').forEach(x=>x.onclick=()=>{db.moments.find(m=>m.id===x.dataset.like).likes++;render()});
  document.querySelectorAll('[data-delgroup]').forEach(x=>x.onclick=()=>{if(confirm('删除整个分组及其中字卡？')){db.cards.textGroups=db.cards.textGroups.filter(g=>g.id!==x.dataset.delgroup);render()}});
  document.querySelectorAll('[data-delcard]').forEach(x=>x.onclick=()=>{const [g,i]=x.dataset.delcard.split(':');db.cards.textGroups.find(a=>a.id===g).items.splice(+i,1);render()});
  document.querySelectorAll('[data-delitem]').forEach(x=>x.onclick=()=>{db.cards[cardTab].splice(+x.dataset.delitem,1);render()});
  document.querySelectorAll('[data-editcard]').forEach(x=>x.onclick=()=>{const [g,i]=x.dataset.editcard.split(':'),o=db.cards.textGroups.find(a=>a.id===g),v=prompt('编辑字卡',o.items[+i]);if(v){o.items[+i]=v;render()}});
  document.querySelectorAll('[data-editgroup]').forEach(x=>x.onclick=()=>{const g=db.cards.textGroups.find(a=>a.id===x.dataset.editgroup),v=prompt('编辑分组名',g.name);if(v){g.name=v;render()}});
  document.querySelectorAll('[data-edititem]').forEach(x=>x.onclick=()=>{const o=db.cards[cardTab][+x.dataset.edititem],v=prompt('编辑内容',o.text);if(v){o.text=v;render()}});
  document.querySelectorAll('[data-message]').forEach(x=>x.oncontextmenu=e=>{e.preventDefault();messageMenu(x.dataset.message)});
  document.querySelectorAll('[data-poke]').forEach(x=>{let last=0;x.ondblclick=()=>poke();x.ontouchend=()=>{const n=Date.now();if(n-last<350)poke();last=n}});
  const fs=document.querySelector('[data-font]');if(fs)fs.oninput=()=>{db.ui.fontSize=+fs.value;document.getElementById('fontVal').textContent=fs.value+'px';save()};
  const rs=document.querySelector('[data-readstyle]');if(rs){rs.value=db.global.readStyle;rs.onchange=()=>{db.global.readStyle=rs.value;save()}}
  document.querySelectorAll('[data-giftstatus]').forEach(x=>x.onclick=()=>{const [id,status]=x.dataset.giftstatus.split(':');db.gifts.find(g=>g.id===id).status=status;render()});
  bindNotes(); setTimeout(()=>{const s=document.getElementById('chatScroll');if(s)s.scrollTop=s.scrollHeight},0);
}
function allowedCards(type){ const r=role();if(type==='text') return db.cards.textGroups.filter(g=>g.roles.includes(r.id)&&r.permissions.text.includes(g.name)).flatMap(g=>g.items);return (db.cards[type]||[]).filter(x=>x.roles.includes(r.id)).map(x=>x.text); }
function sendMessage(e){ e.preventDefault();const input=e.target.message,text=input.value.trim();if(!text)return;const r=role(),msg={id:uid(),from:'me',type:'text',content:text,time:now(),read:false};(db.chats[r.id]??=[]).push(msg);input.value='';render();setTimeout(()=>{if(r.settings.read){msg.read=true;save();render()} if(r.settings.noReply&&chance(28))return; reply();},Math.max(200,r.settings.replySpeed*1000));if(chance(r.settings.favoriteChance))db.favorites.role.push({...msg}); }
function reply(){ const r=role(),pool=allowedCards('text');if(!pool.length){toast('这个角色没有可用的文字字卡');return}let content;if(r.settings.combine){let min=Math.max(1,r.settings.combineMin),max=Math.max(min,r.settings.combineMax),count=min+Math.floor(Math.random()*(max-min+1));content=Array.from({length:count},()=>pick(pool)).join('\n');}else content=pick(pool);db.chats[r.id].push({id:uid(),from:'role',type:'text',content,time:now()});if(chance(r.settings.pokeChance))db.chats[r.id].push({id:uid(),from:'role',type:'notice',content:pick(allowedCards('poke'))||'轻轻碰了碰你',time:now()});save();render(); }
function poke(){ const t=pick(allowedCards('poke'))||'轻轻碰了碰角色';db.chats[role().id].push({id:uid(),from:'me',type:'notice',content:t,time:now()});render(); }
function saveSettings(e){e.preventDefault();const f=new FormData(e.target),r=role(),s=r.settings;r.name=f.get('name').trim()||'角色';['combineMin','combineMax','fontSize'].forEach(k=>s[k]=+f.get(k));s.combineMax=Math.max(s.combineMin,s.combineMax);s.userCss=f.get('userCss');s.roleCss=f.get('roleCss');modal=null;render();scheduleAutomation();}
function addCards(e){e.preventDefault();const f=new FormData(e.target),items=[...new Set(f.get('items').split('\n').map(x=>x.trim()).filter(Boolean))],roles=f.getAll('roles');if(cardTab==='text'){const name=f.get('group').trim();if(!name)return toast('请填写分组名称');let g=db.cards.textGroups.find(x=>x.name===name);if(!g){g={id:uid(),name,items:[],roles};db.cards.textGroups.push(g)}g.items=[...new Set([...g.items,...items])];g.roles=roles;roles.forEach(id=>{const r=db.roles.find(x=>x.id===id);if(r&&!r.permissions.text.includes(name))r.permissions.text.push(name)})}else db.cards[cardTab].push(...items.filter(t=>!db.cards[cardTab].some(x=>x.text===t)).map(text=>({id:uid(),text,roles})));modal=null;render();}
function readFile(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
async function addSticker(e){e.preventDefault();const f=new FormData(e.target),file=f.get('image');if(!file?.size)return toast('请选择图片');db.cards.sticker.push({id:uid(),text:await readFile(file),roles:f.getAll('roles')});modal=null;render()}
async function addRole(e){e.preventDefault();const f=new FormData(e.target),id=uid(),base=defaults().roles[0];const file=f.get('avatar');db.roles.push({...base,id,name:f.get('name')||'角色',avatar:file?.size?await readFile(file):'',permissions:{...base.permissions,text:[]},settings:{...base.settings}});db.chats[id]=[];db.ui.activeRole=id;modal=null;render()}
async function addMoment(e){e.preventDefault();const f=new FormData(e.target),file=f.get('image');db.moments.unshift({id:uid(),author:'me',text:f.get('text'),image:file?.size?await readFile(file):'',time:now(),likes:0,comments:[]});modal=null;render()}
function addDream(e){e.preventDefault();const f=new FormData(e.target);db.dreams.unshift({id:uid(),date:f.get('date'),title:f.get('title'),text:f.get('text')});modal=null;render()}
function addSchedule(e){e.preventDefault();const f=new FormData(e.target);db.schedule.push({id:uid(),title:f.get('title'),date:f.get('date')});render()}
function action(a){
 if(a==='add-role'){modal='role-add';return render()}
 if(a==='avatar'){const p=document.getElementById('filePicker');p.setAttribute('capture','user');p.onchange=async()=>{if(p.files[0]){role().avatar=await readFile(p.files[0]);render()}};p.click()}
 if(a==='reset-settings'){const fresh=defaults().roles[0].settings;role().settings={...fresh};render()}
 if(a==='search'){const q=prompt('搜索聊天记录');if(!q)return;const m=db.chats[role().id].find(x=>x.content.includes(q));if(m){document.getElementById('msg-'+m.id)?.scrollIntoView({behavior:'smooth',block:'center'});toast('已定位到第一条结果')}else toast('没有找到相关记录')}
 if(a==='export'){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='snow-vanilla-backup.json';a.click();URL.revokeObjectURL(u)}
 if(a==='import'){const p=document.getElementById('filePicker');p.removeAttribute('accept');p.removeAttribute('capture');p.onchange=async()=>{try{const x=JSON.parse(await p.files[0].text());if(!x.version)throw 0;db=x;render()}catch{toast('导入失败：不是有效备份')}};p.click()}
 if(a==='clear'&&confirm('第一次确认：确定清空全部数据？')&&confirm('第二次确认：此操作无法撤销，继续吗？')){localStorage.removeItem(KEY);db=defaults();render()}
 if(a==='new-gift'){const name=prompt('礼物名称');if(!name)return;const price=Number(prompt('价格（0～9999，可输入合理小数）','0'));if(!Number.isFinite(price)||price<0||price>9999)return toast('金额需在 0～9999 之间');db.gifts.unshift({id:uid(),from:'me',to:role().id,name,price,content:prompt('图片描述、emoji 内容或留言','')||'',status:'等待角色决定'});setTimeout(()=>{const g=db.gifts[0];g.status=chance(75)?'accepted':'rejected';save()},700);render()}
 if(a==='add-note'){const text=prompt('写下便签');if(text){db.notes.push({id:uid(),from:'me',text,x:15,y:60,w:145,h:100});render()}}
 if(a==='role-note'){const text=pick([...allowedCards('text'),...allowedCards('kaomoji'),...allowedCards('emoji')]);if(text){db.notes.push({id:uid(),from:'role',text,x:180,y:170,w:145,h:100});render()}else toast('没有可用字卡')}
}
function toolAction(a){
 if(['image','camera'].includes(a)){const p=document.getElementById('filePicker');p.accept='image/*';a==='camera'?p.setAttribute('capture','environment'):p.removeAttribute('capture');p.onchange=async()=>{if(!p.files[0])return;db.chats[role().id].push({id:uid(),from:'me',type:'image',content:await readFile(p.files[0]),time:now()});modal=null;render()};return p.click()}
 if(a==='sticker'){const s=pick(allowedCards('sticker'));if(!s)return toast('没有可用表情包');db.chats[role().id].push({id:uid(),from:'me',type:'image',content:s,time:now()});modal=null;return render()}
 if(a==='poke'){modal=null;poke();return}
 if(['transfer','redpacket'].includes(a)){const amount=Number(prompt(`${a==='transfer'?'转账':'红包'}金额（0～9999）`,'0'));if(!Number.isFinite(amount)||amount<0||amount>9999)return toast('金额需在 0～9999 之间');const extra=pick([...allowedCards('text'),...allowedCards('kaomoji'),...allowedCards('emoji')])||'';db.chats[role().id].push({id:uid(),from:'me',type:'text',content:`${a==='transfer'?'转账':'红包'} ¥${amount}${extra?'\n'+extra:''}`,time:now()});setTimeout(()=>{db.chats[role().id].push({id:uid(),from:'role',type:'notice',content:chance(72)?'角色已接受':'角色已拒绝',time:now()});render()},900);modal=null;return render()}
 if(a==='gift-send'){modal='gifts';return render()}
 if(a==='share'){toast('可在聊天消息上右键，选择转发到朋友圈');return}
 if(a==='voice'||a==='video'){modal=null;startCall(a);}
}
function messageMenu(id){const m=db.chats[role().id].find(x=>x.id===id),v=prompt('输入操作编号：1 引用 / 2 撤回 / 3 收藏 / 4 转发朋友圈');if(v==='1')document.querySelector('#composer input').value=`「${m.content.slice(0,28)}」\n`;if(v==='2'){db.chats[role().id]=db.chats[role().id].filter(x=>x.id!==id);db.chats[role().id].push({id:uid(),type:'notice',content:'一条消息已撤回',time:now()});render()}if(v==='3'){db.favorites.mine.push({...m});toast('已收藏')}if(v==='4'){db.moments.unshift({id:uid(),author:'me',text:m.content,image:m.type==='image'?m.content:'',time:now(),likes:0,comments:[]});toast('已转发到朋友圈')}}
async function startCall(type){callState={type,status:'正在呼叫…',seconds:0,min:false,stream:null};if(type==='video'){try{callState.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false})}catch{callState.status='摄像头不可用，已显示头像';toast('浏览器未授权摄像头，已降级为头像')}}render()}
function callView(){if(callState.min)return `<button class="mini-call" data-call="restore">${icon(callState.type==='video'?'video':'phone')} ${formatDuration(callState.seconds)}</button>`;return `<div class="call">${callState.stream?'<video id="localVideo" autoplay muted playsinline></video>':avatar()}<div class="call-info"><h2>${esc(role().name)}</h2><p>${callState.status} · ${formatDuration(callState.seconds)}</p><small>本机画面真实；角色端为模拟逻辑</small></div><div class="call-actions"><button data-call="accept">${icon('phone')}</button><button data-call="min">${icon('chevron')}</button><button class="hang" data-call="hang">${icon('x')}</button></div></div>`}
function formatDuration(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function bindCall(){document.querySelectorAll('[data-call]').forEach(x=>x.onclick=()=>{const a=x.dataset.call;if(a==='accept'){callState.status='通话中';if(!timer)timer=setInterval(()=>{callState.seconds++;render()},1000)}if(a==='min'){callState.min=true;render()}if(a==='restore'){callState.min=false;render()}if(a==='hang'){callState.stream?.getTracks().forEach(t=>t.stop());callState=null;clearInterval(timer);timer=null;render()}});if(callState?.stream){const v=document.getElementById('localVideo');if(v)v.srcObject=callState.stream}}
function bindNotes(){document.querySelectorAll('[data-note]').forEach(el=>{let sx,sy,ox,oy;el.onpointerdown=e=>{if(e.offsetX>el.clientWidth-20&&e.offsetY>el.clientHeight-20)return;sx=e.clientX;sy=e.clientY;ox=el.offsetLeft;oy=el.offsetTop;el.setPointerCapture(e.pointerId)};el.onpointermove=e=>{if(sx==null)return;el.style.left=Math.max(0,ox+e.clientX-sx)+'px';el.style.top=Math.max(0,oy+e.clientY-sy)+'px'};el.onpointerup=()=>{const n=db.notes.find(x=>x.id===el.dataset.note);n.x=el.offsetLeft;n.y=el.offsetTop;n.w=el.offsetWidth;n.h=el.offsetHeight;sx=null;save()}})}
const oldBind=bind;bind=function(){oldBind();bindCall()};
function scheduleAutomation(){clearTimeout(window.proactiveTimer);const s=role().settings.proactiveSeconds;if(s>0)window.proactiveTimer=setTimeout(()=>{reply();scheduleAutomation()},s*1000)}
document.documentElement.style.setProperty('--font',`${db.ui.fontSize}px`);render();scheduleAutomation();
